# 이 파일에선 CI까지만 해볼것임
name: aws-v5
on:
  # push가 되면
  push:
    # main 브랜치에
    branches:
      - main

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build:
    # 우분투 최신버전에서
    runs-on: ubuntu-latest
    steps:
      # 코드 다운로드, 자주쓰는 명령어는 깃액션에서 actions라는 모듈로 제공해줌
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu

      - name: Pemission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
